### ISSUE TITLE
Add a Thread Option

### ISSUE THREAD

**Issue by 641i130** [nylonicious/danbooru-api-downloader#1]
I'm not really familiar with **aiohttp** but I do have to say, this program works really well. 

I just got an error:
```aiohttp.client_exceptions.ServerDisconnectedError```

I think it is because of all the requests the API is receiving because that's what StackOverflow said but I could be wrong. 

Anyways, I love this program! It works like a charm, most of the time.

**Comment by nylonicious** [comment]
I'm pretty sure this error is caused by trying to query too much tags, as some of the sites only support querying 1 or 2 tags at the same time by non registered users. It's really a quick and dirty script i made in few hours and never really thought about doing anything serious with it.

**Comment by ghost** [comment]
I had found that instead of using asyncio.run(), using asyncio.get_event_loop().run_until_complete() fixed that, though I don't know how it'd work with tasks
